
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${SCCS_GIT_URI}
          username: ${SCCS_GIT_USERNAME}
          password: ${SCCS_GIT_ACCESS_TOKEN}
          clone-on-start: true
          default-label: master
  security:
    user:
      name: ${SCCS_USER}
      password: ${SCCS_PASSWORD}

encrypt:
  keyStore:
    location: ./config-server.jks
    password: ${SCCS_STOREPASS}
    alias: config-server-key
    secret: ${SCCS_KEYPASS}
